name: deploy_on_server CI

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    # To run on a private server
    runs-on: self-hosted

    strategy:
      matrix:
        # Specify the python version if multiple use ,
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4 
    - uses: actions/setup-python@v3
    - name: use python ${{ matrix.python-version }}
      with: 
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        python -m pip install --upgrade pip
        pip install flask
        
    - name: Run flask app
      run: python app.py
