name: deploy_on_server CI

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    # To run on a private server
    runs-on: self-hosted

    # strategy:
    #   # Specify the python version if multiple use ,
    #   python-version: '3.12'

    steps:
    - uses: actions/checkout@v4 

    - name: Check if Python 3.12 is available
      run: |
        if ! python3.12 --version >/dev/null 2>&1; then
          echo "Python 3.12 is not available, installing..."
          sudo apt-get update
          sudo apt-get install -y python3.12
        fi
        
    - name: use python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        python -m pip install --upgrade pip
        pip install flask
        
    - name: Run flask app
      run: python app.py
